In [32]:
import pandas as pd
df = pd.read_csv('../csv/stock.csv')

In [33]:
df.head(10)

,id,Category_id,Supplier_id,Name,image,Unit_id,Subunit_id,Contains,subunit_replenish_qty,Buying_price,Discount,Price,Opening_stock,Quantity,Restock_Level,Created_at,Updated_at
0,18,4,3,Beef Whole Kg(s),1645802086.png,10,1,0,0,440,0,600,46.36,0.101651,5,2022-02-25 09:14:46,2023-06-11 12:38:51
1,19,4,3,Beef Rib-Eye.,1645802796.png,10,1,0,0,400,0,500,0.00,0.000000,2,2022-02-25 09:26:36,2022-09-01 02:08:23
2,20,4,3,Top Side Steak,1645802888.png,10,1,0,0,400,0,600,0.00,0.000000,2,2022-02-25 09:28:08,2022-09-01 02:08:20
3,21,4,3,Silver Side Steak,1645803081.png,10,1,0,0,400,0,600,0.00,0.000000,2,2022-02-25 09:31:21,2022-09-01 02:08:15
4,22,4,3,Beef Rump Steak,1645803195.png,10,1,0,0,400,0,600,0.00,0.000000,20,2022-02-25 09:33:15,2023-01-10 14:24:25
5,23,4,3,Meat On Bone Kg(s),1645803264.png,10,1,0,0,450,0,600,0.00,13.895700,5,2022-02-25 09:34:24,2023-06-13 13:19:10
6,24,4,3,Beef Top Rump.,1645803412.png,10,1,0,0,400,0,600,0.00,0.000000,2,2022-02-25 09:36:52,2022-09-01 02:08:13
7,25,4,3,Regular Minced Meat,1645803526.png,10,1,0,0,320,0,700,0.00,29.327900,5,2022-02-25 09:38:46,2023-06-13 12:51:18
8,26,4,3,Lean Minced Meat,1645803581.png,10,1,0,0,400,0,700,0.00,0.060000,2,2022-02-25 09:39:41,2023-01-15 03:59:54
9,27,4,3,Beef Bones Kg(s),1645803667.png,10,1,0,0,100,0,150,0.00,1.358340,0,2022-02-25 09:41:07,2023-06-13 06:13:50

In [34]:
headers = list(df.columns)
headers

['id',
 'Category_id',
 'Supplier_id',
 'Name',
 'image',
 'Unit_id',
 'Subunit_id',
 'Contains',
 'subunit_replenish_qty',
 'Buying_price',
 'Discount',
 'Price',
 'Opening_stock',
 'Quantity',
 'Restock_Level',
 'Created_at',
 'Updated_at']

In [35]:
df = df.rename(columns={'Category_id': 'category_id',
                        'Name': 'product_name',
                        'Unit_id': 'unit_id',
                        'Subunit_id': 'sub_unit_id',
                        'Contains': 'contains',
                        'Quantity': 'total_qty',
                        'Restock_Level': 'restock_level'})

In [36]:
headers = list(df.columns)
headers.remove('id')
headers.remove('Created_at')
headers.remove('Updated_at')
headers.remove('Supplier_id')
headers.remove('Buying_price')
headers.remove('Discount')
headers.remove('Opening_stock')
headers

['category_id',
 'product_name',
 'image',
 'unit_id',
 'sub_unit_id',
 'contains',
 'subunit_replenish_qty',
 'Price',
 'total_qty',
 'restock_level']

In [37]:
"""
excluded_headers = ['Price']
for i, row in df.iterrows():
  values = {header: row[header] for header in headers if header not in excluded_headers}
  values['product_description'] = 'Product Description'
  with open('../query_scripts/products.py', 'a') as fp:
      fp.write('create_product(**'+str(values)+')\n')
"""

"\nexcluded_headers = ['Price']\nfor i, row in df.iterrows():\n  values = {header: row[header] for header in headers if header not in excluded_headers}\n  values['product_description'] = 'Product Description'\n  with open('../query_scripts/products.py', 'a') as fp:\n      fp.write('create_product(**'+str(values)+')\n')\n"

In [39]:
counter = 1
for i, row in df.iterrows():
  values = {}
  for header in headers:
    values['product_id'] = counter
    values['supplier_id'] = 1
    values['qty_purchased'] = row['total_qty']
    values['current_qty'] = row['total_qty']
    values['damaged'] = 0
    values['buying_price'] = row['Price'] / 2
    values['selling_discount'] = 0
    values['selling_price'] = row['Price']
    values['expiry_date'] = '2023-06-30'
  counter = counter + 1
  with open('../query_scripts/product_batches.py', 'a') as fp:
      fp.write('create_product_batch(**'+str(values)+')\n')